### ISSUE TITLE
Issue Installing 

### ISSUE THREAD

**Issue by derekjohnsonzethcon** [StrobeTechnologiesLtd/OSTCheckList#2]
When installing it creates a whole bunch of text above my pages. See attached.
![ckeck-list error](https://cloud.githubusercontent.com/assets/13395856/9288742/9c93f9d0-431c-11e5-8b4b-18a5d31b5761.PNG)

**Comment by robintoy** [comment]
Looks like you have not gone to the plug-in section of osTicket and installed it.

Kind Regards
Robin

Robin Toy
Director
Strobe Technologies Ltd

Sent from my Windows Phone

**Comment by derekjohnsonzethcon** [comment]
ronintoy,

This is what happens when I install it. Just FYI I am running osTicket version 1.9.11

**Comment by robintoy** [comment]
Mmmm ok,

Been awhile since I have done an install as all worked lol.

Will have to look at getting test system up

Kind Regards
Robin

Robin Toy
Director
Strobe Technologies Ltd

Sent from my Windows Phone

**Comment by derekjohnsonzethcon** [comment]
Robin,

If you like i can get you access to my system. We can use teamviewer if you can

**Comment by robintoy** [comment]
Hi Derek,

That would be great but not sure I can do that today as have friends come round soon to which I better do something for.

The screenshot you have sent looks like the main screen after installation indeed, but is displaying code not the page which is odd.

So the osTicket plugin installer didn't display any errors and shows as version 0.1.6 or greater?

Kind Regards
Robin

Robin Toy
Director
Strobe Technologies Ltd

Sent from my Windows Phone

**Comment by derekjohnsonzethcon** [comment]
robintoy,

I agree, I need to get off of here too. As far as I can tell the install went without a hitch becasue you can make configuration changes but im sure the DB changes are missing. The version on the plugin installer is telling me 0.1.9

![ckeck-list ver 0 1 9](https://cloud.githubusercontent.com/assets/13395856/9289132/8524be38-432b-11e5-9946-eeff4f681d74.PNG)

Configuration options

![ckeck-list config setting available](https://cloud.githubusercontent.com/assets/13395856/9289143/fadefa12-432b-11e5-8ebc-c3f912eb5e87.PNG)

**Comment by yisraelU** [comment]
i am having the same problem with the install . Also running the latest version 1.9.11

**Comment by robintoy** [comment]
Hi Guys,

found an issue with the installation SQL which I have now updated and will be on here shortly.

**Comment by yisraelU** [comment]
still ran into the error

**Comment by yisraelU** [comment]
tried running the code directly in the database and produced errors.
was this written for mysql or sql?

**Comment by robintoy** [comment]
This is written in SQL with a few changes to the code to be osTicket compliant.

Change the $ symbol at end of lines to a ; for MySQL

Kind Regards
Robin

Robin Toy
Director
Strobe Technologies Ltd

Sent from my Windows Phone

**Comment by robintoy** [comment]
Hi @derekjohnsonzethcon & @yisrael1981 
have a look at the new release of this as I hope this has solved it!

**Comment by derekjohnsonzethcon** [comment]
@robintoy,

I'll test it in a bit.

**Comment by derekjohnsonzethcon** [comment]
@robintoy 

I did get a chance to try to install it earlier and came across the same issue that I was getting with the code on the page. Below is additional information that I recieved 

[DELETE FROM ost_ticket_lock WHERE expire<NOW()]

You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1175', '[DELETE FROM os...')<br />
#1 (root)/include/class.lock.php(153): db_query('DELETE FROM ost...')<br />
#2 (root)/include/class.cron.php(32): TicketLock::cleanup()<br />
#3 (root)/scp/autocron.php(57): Cron::TicketMonitor()<br />
#4 {main}

**Comment by robintoy** [comment]
Hi @derekjohnsonzethcon 
thanks for testing.

So odd why you getting those errors, none of the plugin uses that code as it all part of osTicket classes built in to the system.

I have just added a commit to the develop branch which disables all the SQL install and uninstall from within osTicket, along with cleaning up some other lines of the plugin setup.

It's working like a dream here which is so odd. Can I ask you create the DB tables manually using the following code and try it again?

``` SQL
CREATE TABLE IF NOT EXISTS `ost_checklist` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `orde` int(11) NOT NULL,
  `menu_id` int(11) NOT NULL default '0',
  `indent` int(11) NOT NULL default '0',
  `header` int(11) NOT NULL default '0',
  `period` int(11) NOT NULL default '0',
  `tekst` varchar(250) default NULL,
  `disabled` int(11) NOT NULL default '0',
  `start` date NOT NULL,
  `help` text NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `orde` (`orde`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ost_checklist_entries` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `datum` datetime default NULL,
  `door` varchar(30) default NULL,
  `ref` int(11) default NULL,
  `tekst` text,
  `status` int(11) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `datum` (`datum`),
  KEY `ref` (`ref`),
  FULLTEXT KEY `tekst` (`tekst`),
  FULLTEXT KEY `volletekst` (`tekst`,`door`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
```

**Comment by Dorian-Grim** [comment]
@robintoy 
I just tested. I created the tables in advance, I used the last version of the plugin, after install the text appeared. At the bottom of the page I saw the plugin and clicked on it, I got 
![image](https://cloud.githubusercontent.com/assets/24250692/21140795/932512da-c142-11e6-925c-110a1d8482db.png)

**Comment by robintoy** [comment]
Hi @Dorian-Grim 
which version of osTicket are you using?

**Comment by Dorian-Grim** [comment]
1.9.14

**Comment by robintoy** [comment]
very odd indeed....
Being honest, we have not used this plugin for an age now as moved away to Comodo ServiceDesk (custom version of osTicket).

Is this mod something that would be of interest or help to you?

**Comment by Dorian-Grim** [comment]
Yes, it would...
